twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['base_form.html.twig']
    globals:
        app_name: '%app.name%'
        app_version: '%app.version%'
        app_signature: '%app.signature%'
        

    
